version: "3.9"
services:

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    networks:
      - quotation-management-network
    volumes:
      - /var/lib/mysql

    
  stockmanager:
    image: lucasvilela/stock-manager
    container_name: stockmanager
    ports:
      - 8080:8080
    networks:
      - quotation-management-network
    depends_on:
      - mysql

  quotationmanagement:
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: jp-fonseca/quotation-management
    container_name: quotation-management
    ports:
      - 8081:8081
    environment:      
      - PORT=8081
      - MYSQL_CONTAINER=mysql
      - STOCK_MANAGER_CONTAINER=stockmanager
    networks:
      - quotation-management-network
    depends_on:
      - stockmanager
      - mysql
      
  
networks:
  quotation-management-network:
    driver: bridge